### PR TITLE
CSS / JS compression via local YUI Compressor jar

### PR DESCRIPTION
**Pull request by alechill**
Hi,

Really useful project, but did not do exactly what I needed, so thought I'd give it a bit of a once over...

Have added CSS and JS compression via a local YUI Compressor jar....this is because Google Compiler web service cannot always be trusted to be reachable (ie if have no internet connection), it also has limits on the number of files that can be processed within a certain amount of time (bad news when you have your JS files split into a file per class), and has no support for CSS, which you would usually want to be compressed at same time as JS

Have tried to do it in a non-intrusive manner, preserving all the existing functionality and config settings. Hope it's of some use

Thanks

Alec

### CODE REVIEW

**Comment by dsimard** [comment]
Hi,
happy to see that. I'll take a look at it shortly and get back to you.

Thanks!

**Comment by alechill** [comment]
Hi,

Cool, have also added ignoring of specified files, and being able to configure how you want JSLint to check your files.

Alec

**Comment by dsimard** [comment]
Hi,
that's a lot of code ;)

It would be great if you would add some tests for your code. I personally hate to write them but I want the project to be solid. Take a look at this file : https://github.com/dsimard/ready.js/blob/master/test/test.js . 

Thanks!

**Comment by dsimard** [comment]
I had too much trouble integrating it to my version and the tests didn't work. Sorry...

**Pull request closed without merging**
